### ISSUE TITLE
[구현] 세부 구현 내용 Advanced 리스트

### ISSUE THREAD

**Issue by lain-alice** [codestates-seb/seb43_main_016#222]
### Discussed in https://github.com/codestates-seb/seb43_main_016/discussions/152

<div type='discussions-op-text'>

<sup>Originally posted by **serveman** May 14, 2023</sup>
# 우선순위 3

### 스터디 기능
- [ ] 스터디 맴버 권한 이전 - PATCH - 스터디장만 가능
- [ ] 스터디장 탈퇴 - 불가능 - 안내 문구 출력할 수 있도록 해야 함
- [ ] 스터디 모집글 상태 변경 - PATCH - 엔드포인트를 통해서 모집글 상태를 변경할 수 있음
<br>

# 우선순위 4
### 스터디 관리 ( 모집 )
- [ ] 스터디 모집글 상태 관리 - PATCH - 모집중 / 모집완료 로 구분할 수 있도록 한다
- [ ] 스터디 모집이 완료된 경우, 개인 캘린더에 일정을 적용 - PATCH - 개인 캘린더에 스터디 일정을 자동으로 추가
- [ ] 스터디 모집글 중 일정이 수정된 경우, 개인 캘린더에 자동으로 반영 - PATCH - 개인 캘린더에 자동으로 반영
- [ ] 스터디 삭제 시, 개인 캘린더에 자동으로 반영 - DELETE - 개인 캘린더에 자동으로 반영
<br>

### 태그 기능
- [ ] 태그 조회 - GET - 사용자에게 검색 페이지를 제공한다 ( 태그 전체 내용 조회 )
- [ ] 태그 조회 - GET - 검색할 때 이용할 수 있는 태그의 목록을 제공한다
<br>

세부 구현 리스트 바탕으로 해당되는 부분 정리해봤는데...우선 최소 사항부터 마무리하겠습니다ㅠㅜ

**Comment by serveman** [comment]
3,4번만 진행하시면 됩니다. 5,6번은 안하기로했어요

**Comment by serveman** [comment]
작업 내용은 따로 위에 이슈로 만드셨으니 이건 클로즈 하겠습니다 !
