### ISSUE TITLE
[구현] 최소 요구 사항 미완성된 부분들 (이승현)

### ISSUE THREAD

**Issue by lain-alice** [codestates-seb/seb43_main_016#225]
# 우선순위 1 

## 스터디 모집
- [X] 스터디 모집글 등록을 정상적으로 성공한다
  - [ ] 날짜, 시간 입력창을 Date() 객체와 관련 라이브러리로 구현하여 데이터 전송한다
- [ ] 스터디 모집글 수정을 정상적으로 성공한다
- [x] 스터디 모집글 삭제를 정상적으로 성공한다
- [x] 스터디 모집글 리스트를 조회한다    
- [x] 스터디 모집글 내용을 조회한다
<br>

# 우선순위 2

## 스터디 모집
- [x] 스터디 가입 신청을 정상적으로 성공한다
- [x] 스터디 모집글 상태를 정상적으로 표시한다
- [x] 스터디 모집글에 작성자의 Profile을 추가한다
- [ ] 스터디 모집글에 타이틀 이미지를 등록한다
- [ ] 스터디 리스트에서 타이틀 이미지를 조회한다

## 댓글 기능
- [x] 스터디 댓글을 정상적으로 등록, 조회, 수정, 삭제한다
  - [x] 로그인한 회원에 한해 스터디에 댓글을 등록한다
  - [x] 스터디 모집글 내에서 댓글을 조회한다
  - [x] 본인에 한해 스터디의 댓글을 수정한다
  - [x] 본인에 한해 스터디의 댓글을 삭제한다
  - [ ] 스터디장은 어느 회원의 댓글이든 수정, 삭제한다

## 태그 기능
- [x] 서버에 존재하는 태그 목록을 요청하여, 리스트 형태로 사용자에게 태그 목록을 보여주면 선택한다
- [x] 선택한 태그를 스터디 모집글 리스트, 내용에서 조회한다
- [x] 등록된 태그 수정, 삭제를 정상적으로 성공한다
<br>

우선순위 1은 무조건, 우선순위 2는 최대한 끝까지 구현해보도록 하겠습니다ㅠㅜㅜ!!

**Comment by serveman** [comment]
- 스터디장은 어느 회원의 댓글이든 수정, 삭제한다 -> 삭제는 가능하지만, 수정은 하면 안됩니다. 위험한 기능이에요
