### ISSUE TITLE
[수정] 서버의 CORS 설정

### ISSUE THREAD

**Issue by serveman** [codestates-seb/seb43_main_016#285]
## 목적
- 서버를 외부 공격으로부터 보호하기 위해 CORS 설정 등을 해야합니다.
- 사용자의 접속 창구는 프론트의 메인 페이지만으로 합니다.
<br>

## 필요 작업
- [x] CORS 설정
<br>

> 이후 추가 작업 있으시면 남겨주세요 !

**Comment by wish9** [comment]
도메인 설정해두면 FE분들 로컬에서 테스트하시기 힘들어져서 api요청처리 전부 완료된 다음에 적용하겠습니다.
