### ISSUE TITLE
[구현] 스터디 관리 페이지

### ISSUE THREAD

**Issue by Whaleinmilktea** [codestates-seb/seb43_main_016#60]
멤버(스터디 그룹의 장)
- [ ] 스터디 그룹의 장이 속한 스터디 그룹의 멤버 조회
- [ ] 스터디 그룹의 장이 속한 스터디 그룹의 멤버 신청 승인
- [ ] 스터디 그룹의 장이 속한 스터디 그룹의 멤버 신청 거절
- [ ] 스터디 그룹의 장이 속한 스터디 그룹의 해체
- [ ] 스터디 그룹의 장이 속한 스터디 그룹의 멤버 강제탈퇴
- [ ] 스터디 그룹의 장이 스터디 그룹의 장 권한 위임
- [ ] 스터디 그룹의 장이 속한 스터디 일정을 수정
- [ ] 스터디 그룹의 장이 속한 스터디 일정을 삭제

멤버(스터디 그룹의 멤버)
- [ ] 멤버가 속한 스터디 그룹의 멤버 조회
- [ ] 멤버가 속한 스터디 그룹에서 탈퇴

**Comment by Whaleinmilktea** [comment]
기능 중심으로 코드를 전반적으로 개편하고자 완료된 모든 issue를 개편했습니다.

**Comment by serveman** [comment]
기존 내용 클로즈 하겠습니다 !
