### ISSUE TITLE
[구현] Entity 구조 변경

### ISSUE THREAD

**Issue by serveman** [codestates-seb/seb43_main_016#90]
## 연관관계 구조 변경
- [x] member 와 classmate 관계 변경 ( 1:N )
- [x] classmate 에서 member 로 Study 댓글 관계 변경 ( 1:N )
<br>

* classmate 와 studygroup 관계 변경
- [x] 스터디장 : 스터디그룹 = 1:N
- [x] 스터디원 : 스터디그룹 = N:1
<br>

- [x] 조인테이블 삭제

**Comment by wish9** [comment]
변경사항 확인했습니다.
